name: GTest CI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Check out the repository code

    - name: Set up CMake and GTest
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libgtest-dev build-essential

    - name: Create build directory
      run: mkdir -p build  

    - name: Configure CMake
      working-directory: .  
      run: cmake -S . -B build  

    - name: Build project
      working-directory: .  
      run: cmake --build build  

    - name: Run tests
      working-directory: ./build  
      run: ./tests/test_tweetnacl  # Run the test executable